server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Serve the static assets correctly
    location /assets/ {
        try_files $uri =404;
    }

    # Fallback routing for React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
